feat: update to solidity 0.7.0
Truffle flattener is not working due this error

Error: Could not parse ./contracts/BaseToken.sol for extracting its imports: Error: Constructors have to be declared either "public" or "internal"